/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteImport } from './routes/$project'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChordsIndexRouteImport } from './routes/chords/index'

const ProjectRoute = ProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordsIndexRoute = ChordsIndexRouteImport.update({
  id: '/chords/',
  path: '/chords/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$project': typeof ProjectRoute
  '/chords': typeof ChordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$project': typeof ProjectRoute
  '/chords': typeof ChordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$project': typeof ProjectRoute
  '/chords/': typeof ChordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$project' | '/chords'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$project' | '/chords'
  id: '__root__' | '/' | '/$project' | '/chords/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectRoute: typeof ProjectRoute
  ChordsIndexRoute: typeof ChordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$project': {
      id: '/$project'
      path: '/$project'
      fullPath: '/$project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chords/': {
      id: '/chords/'
      path: '/chords'
      fullPath: '/chords'
      preLoaderRoute: typeof ChordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectRoute: ProjectRoute,
  ChordsIndexRoute: ChordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
